name: Check latest WIS version

on:
  schedule:
    - cron: '15 */6 * * *'
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the latest version of WIS
        run: |
          curl -s https://api.github.com/repos/toverainc/willow-inference-server/branches/main | jq -r '.commit.sha' > version
          echo "WIS_VERSION=$(cat version)" >> $GITHUB_ENV
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Version updated to: ${{ env.WIS_VERSION }}'
